name: CI
on: push

env:
  BINARY_PATH: brut.apktool/apktool-lib/src/main/resources/prebuilt
  RENDIIX_URL: https://github.com/rendiix/termux-aapt/raw/refs/heads/main/prebuilt-binary

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          repository: 'iBotPeaches/Apktool'
          ref: 'v2.10.0'
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup aapt and aapt2
        run: |
          wget -q $RENDIIX_URL/arm/aapt -O $BINARY_PATH/linux/aapt
          wget -q $RENDIIX_URL/arm/aapt2 -O $BINARY_PATH/linux/aapt2
          wget -q $RENDIIX_URL/arm64/aapt -O $BINARY_PATH/linux/aapt_64
          wget -q $RENDIIX_URL/arm64/aapt2 -O $BINARY_PATH/linux/aapt2_64

      - uses: gradle/actions/setup-gradle@v4
      
      - name: Build +Android
        run: ./gradlew build shadowJar proguard

      - uses: actions/upload-artifact@v4
        with:
          name: apktool.jar
          path: brut.apktool/apktool-cli/build/libs/apktool-v*
